#!/bin/bash
# Running this script requires gcloud command line tools. To install go to https://cloud.google.com/sdk/docs/quickstarts
# See readme.md to understand the variables used in this script

export KEYS_DIR=/opt/sa
export ORGANIZATION_ID="insertyourorganizationID"
export GROUP_NAME="mygroup@mydomain.com"
export PROJECT_BASE_NAME="myprojectbasename"
export FIRST_PROJECT_NUM=1
export LAST_PROJECT_NUM=12
export SA_EMAIL_BASE_NAME="insertuniquename"
export FIRST_SA_NUM=1
export NUM_SAS_PER_PROJECT=100
export CYCLE_DELAY=1s                  # If issues with Google back end not recognizing SAs increase this number. Set = 0 for no delay
export SECTION_DELAY=15s               # If issues with Google back end not recognizing SAs increase this number. Set = 0 for no delay


create_projects() {
    export PROJECT=$1
    echo -e "Create project = $PROJECT"
    gcloud projects create $PROJECT --organization=$ORGANIZATION_ID
    sleep $CYCLE_DELAY
}

enable_apis() {
    export PROJECT=$1
    echo -e "Enable apis for project = $PROJECT"
    gcloud config set project $PROJECT
    gcloud services enable drive.googleapis.com
    sleep $CYCLE_DELAY
    gcloud services enable sheets.googleapis.com
    sleep $CYCLE_DELAY
}

create_sas() {
    export PROJECT=$1
    echo -e "Create service accounts for project = $PROJECT"
    let LAST_SA_NUM=$COUNT+$NUM_SAS_PER_PROJECT-1
    for name in $(seq $COUNT $LAST_SA_NUM); do
        saname="$SA_EMAIL_BASE_NAME""$name"
        echo -e "Creating service account for $saname@$PROJECT == $name in project $1"
        gcloud iam service-accounts create $saname  --display-name=$saname
        sleep $CYCLE_DELAY
    done
    let COUNT=$COUNT+$NUM_SAS_PER_PROJECT
}

create_keys() {
    export PROJECT=$1
    echo -e "create json keys for $PROJECT"
    let LAST_SA_NUM=$COUNT+$NUM_SAS_PER_PROJECT-1
    for name in $(seq $COUNT $LAST_SA_NUM); do
        saname="$SA_EMAIL_BASE_NAME""$name"
        echo -e "creating json keys for $saname@$PROJECT == $name in project $1"
        gcloud iam service-accounts keys create $KEYS_DIR/$name.json --iam-account=$saname@$PROJECT.iam.gserviceaccount.com
        #   NEED to fix syntax for below command to add SA email to group
        #   gcloud iam service-accounts add-iam-policy-binding "$saname@$PROJECT.iam.gserviceaccount.com" --member="group:$GROUP_NAME" --role="roles/viewer"
        echo "$GROUP_NAME,$saname@$PROJECT.iam.gserviceaccount.com,USER,MEMBER" | tee -a $KEYS_DIR/members.csv $KEYS_DIR/allmembers.csv
        sleep $CYCLE_DELAY
    done
    let COUNT=$COUNT+$NUM_SAS_PER_PROJECT
}

main() {
    mkdir -p $KEYS_DIR
    [ -f $KEYS_DIR/members.csv ] && cat $KEYS_DIR/members.csv >> $KEYS_DIR/allmembers.csv && sort -uo $KEYS_DIR/allmembers.csv $KEYS_DIR/allmembers.csv
    echo "Group Email [Required],Member Email,Member Type,Member Role" >$KEYS_DIR/members.csv
    for function in create_projects enable_apis create_sas create_keys ; do
        COUNT=$FIRST_SA_NUM
        for project_num in $(seq $FIRST_PROJECT_NUM $LAST_PROJECT_NUM); do
            $function $PROJECT_BASE_NAME$project_num
            sleep $SECTION_DELAY
        done
    done
}

main
