#!/bin/bash
# Simple script to add / update the display name for your existing service accounts

# Add a filter if you only want to include some projects e.g. "sacopy" for sacopy1, sacopy2 etc
FILTER_PROJECTS=""
# Add a unique identifier for user or account for tracking activity e.g. "user@domain"
UNIQUE_ID=""

proj_list=`gcloud projects list --sort-by=PROJECT_ID | grep "$FILTER_PROJECTS" | cut -d' ' -f1`

for project in $proj_list;do
  gcloud config set project $project
  echo -e "Project name is $project \n"
  sa_list=`gcloud iam service-accounts list --format='value(email)' | sort`
  for sa in $sa_list;do
    sa_name="$UNIQUE_ID${sa%@*}"
    echo -e "Service Account is $sa"
    echo -e "Service Account Name is ${sa%@*}"
    gcloud iam service-accounts update $sa --display-name "$sa_name"
  done
done